### ISSUE TITLE
Remove inefficiency from iteration

### ISSUE THREAD

**Issue by jeremyf** [Sabotnik/euler#1]
The following code is not "efficient". Converting a Range object into an Array is not necessary. Please reference the Range documentation to see if you can do this with less method calls.

```ruby
def array
(1...1000).to_a
end

array.each { |i| 
```

From [challenge1.rb](https://github.com/Sabotnik/euler/blob/0498e2db70f5137a81b1102efd49ccf1fd3428d9/challenge1.rb#L10-L14
)

**Comment by Sabotnik** [comment]
Rewrote it a bit with less method calls
