### ISSUE TITLE
Convert your solution to a callable method

### ISSUE THREAD

**Issue by jeremyf** [Sabotnik/euler#2]
I'd really like to see a callable method that I can pass in a parameter that defines the outer bounds of the Range of integers to sum. The method should return an integer (sum of the Range of numbers that are divisible by 3 or 5).

Below is an example.

```ruby
# your code
puts sum_of_divisibles_up_to(10)
puts sum_of_divisibles_up_to(1000)
```

**Comment by Sabotnik** [comment]
Can you point me in the right direction in documentation? Completed #1 relatively quickly but not sure where to start on this - Google search for "callable method in ruby" returns nil in terms of useful info. Is it creating a class or a method sum_of_divisibles_up_to ?

**Comment by jeremyf** [comment]
I suppose what I meant by "callable method" is a method (callable is usually implied).

```ruby
def sum_of_divisibles_up_to(an_integer)
  # Do stuff here!
end

puts sum_of_divisibles_up_to(10)
```

**Comment by Sabotnik** [comment]
I had that part figured out once I thought about it a bit and that reinforced a bit. I was trying to skip to the end again instead of doing 1 step/change and testing. I forgot I had to move sum = 0 inside the method...
